services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    hostname: librespeed
    restart: always
    networks:
      macvlan:
        ipv4_address: ${librespeed4}
        mac_address: ${librespeedmac}

networks:
  macvlan:
    external: true
    name: ${MACVLAN_NET}